version: '3.9'
services:
  login_ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: login-ui
    stdin_open: true
    volumes:
      - type: bind
        source: ./ui
        target: /app
    environment:
      - CHOKIDAR_USEPOLLING=true

  login_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: login-backend
    volumes:
      - type: bind
        source: ./backend/app
        target: /code/app
